#!/usr/bin/env bash
# Change nginx user permissions and listen to port 8080
chmod 655 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sed -i '1iuser nginx;' /etc/nginx/nginx.conf
lsof -ti tcp:8080 | xargs kill
sudo -u nginx service nginx restart
