#!/usr/bin/env bash
# Change nginx user permissions and listen to port 8080
chmod 755 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
xargs kill
sudo -u nginx service nginx restart
