#!/usr/bin/env bash
#load balancing
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server server 4809-web-01 54.234.216.71::80 check
        server 4809-web-02 54.208.166.207:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
