#!/usr/bin/env bash
# comment
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
load_balance_config=\
"frontend firstbalance
        bind *:80
        option forwardfor
        default_backend webservers
backend webservers
        balance roundrobin
        server makuo4809-web-01 52.73.182.183:80 check
        server makuo4809-web-02 54.226.199.160:80 check
        option httpchk
"
sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cf
sudo echo $load_balance_config >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
